### ISSUE TITLE
Updating variable bound to checked doesnt update switch if readonly or disabled

### ISSUE THREAD

**Issue by mistahenry** [Panman8201/ember-bootstrap-switch#8]
Why can't the switch be updated if readonly or disabled? I have a legitimate use case where I don't want to allow the switch to be changed, but changing other state will ultimately change the state of this switch. I would rather leave as a switch for consistency of UI

**Comment by Panman82** [comment]
That is actually an issue with the `bootstrap-switch` plugin, not a limitation of this addon. There are several issues started over there you can subscribe to:

nostalgiaz/bootstrap-switch#501
nostalgiaz/bootstrap-switch#494
nostalgiaz/bootstrap-switch#442
